default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: root
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: hackerboard_development

test:
  <<: *default
  database: hackerboard_test

production:
  <<: *default
  database: hackerboard_production
  username: hackerboard
  password: <%= ENV['HACKERBOARD_DATABASE_PASSWORD'] %>
