# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure('2') do |config|
  config.vm.box      = 'rodrigoguedes/rails-dev-box'
  config.vm.hostname = 'rodrigo-rails-dev-box'
  config.vm.box_version = "2"
  config.vm.boot_timeout = 6000

  # private network setup
  config.vm.network :private_network, ip: '192.168.50.2'

  config.vm.synced_folder '../../src', '/Projects'

  forwarded_port = ->(guest, host = guest) do
    config.vm.network :forwarded_port,
      guest: guest,
      host: host,
      auto_correct: true
  end

  forwarded_port[3000]    #rails
  forwarded_port[1080]    #mailcatcher
  forwarded_port[3306]    #mysql
  forwarded_port[9200]    #elasticsearch
  forwarded_port[5601]    #kibana

  # config.vm.network :forwarded_port, guest: 3000, host: 3000, auto_correct: true

  config.vm.provider 'virtualbox' do |v|
    v.cpus   = 2
    v.memory = "8192"
    # VM Customizations go here
    v.customize ['modifyvm', :id, '--usb', 'off']
    v.customize ['modifyvm', :id, '--usbehci',  'off']

    # https://github.com/rails/rails/issues/16678
    #v.customize ["guestproperty", "set", :id, "--timesync-threshold", 5000]
    # https://linuxize.com/post/how-to-set-or-change-timezone-in-linux/

  end
end
